:global:
  componentName: thanos
  githubUrl: https://github.com/projectsyn/component-thanos
  feature_goUnitTests: false
  feature_goldenTests: true

.github/workflows/test.yaml:
  matrix:
    key: instance
    entries:
      - defaults
      - store
      - openshift-rbac-proxy
  makeTarget: test -e instance=${{ matrix.provider }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.provider }}

docs/antora.yml:
  name: thanos
  title: Thanos

.gitignore:
  additionalEntries:
    - jsonnetfile.json
