:global:
  componentName: Thanos
  githubUrl: https://github.com/projectsyn/component-thanos
  feature_goUnitTests: false
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - all-in-one-1-18
      - all-in-one
      - openshift-rbac-proxy

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}

.gitignore:
  additionalEntries:
    - jsonnetfile.json
