:global:
  componentName: thanos
  githubUrl: https://github.com/projectsyn/component-thanos
  feature_goUnitTests: false
  feature_goldenTests: true

.github/workflows/test.yaml:
  matrix:
    key: instance
    entries:
      - defaults
      - all-in-one-1-18
      - all-in-one
      - openshift-rbac-proxy
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}

docs/antora.yml:
  name: thanos
  title: Thanos

.gitignore:
  additionalEntries:
    - jsonnetfile.json
