= Parameters

The parent key for all of the following parameters is `thanos`.

== `namespace`

[horizontal]
type:: string
default:: `syn-thanos`

The namespace in which to deploy this component.

== `createNamespace`

[horizontal]
type:: bool
default:: `true`

If this parameter is set to `false, the component won't create the specified namespace.
This is required for all but one instance if multiple component instances are deployed into the same namespace.

== `cluster_kubernetes_version`

[horizontal]
type:: string
default:: `"1.18"`

The Kubernetes version of the cluster on which the component is deployed.

== `jsonnetfile_parameters`

[horizontal]
type:: dict

Parameters for rendering the `jsonnetfile.jsonnet`.
We pass parameter `cluster_kubernetes_version` and cluster fact `distribution` to Jsonnet to enable smart dependency version selection for the `kube-thanos` and `thanos-mixin` Jsonnet libraries.

This is necessary because we need to ensure that this component and other components (for example `rancher-monitoring` and `openshift4-monitoring`) use the same `kube-thanos` and `thanos-mixin` library versions.

Otherwise we get random changes in the cluster catalog at best and incompatible library versions at worst depending on which dependency version wins when `jsonnet-bundler` fetches the Jsonnet libraries.

=== `jsonnetfile_parameters.thanos_mixin_version`

[horizontal]
type:: string
default:: `''`

This parameter is used as the library version for `thanos-mixin` over the autodetected version based on the cluster's Kubernetes version and distribution.

Only set this parameter if you really need a specific `thanos-mixin` version for this component and have read the parameter description for `jsonnetfile_parameters` carefully.

=== `jsonnetfile_parameters.kube_thanos_version`

[horizontal]
type:: string
default:: `''`

This parameter is used as the library version for `kube-thanos` over the autodetected version based on the cluster's Kubernetes version and distribution.

Only set this parameter if you really need a specific `kube-thanos` version for this component and have read the parameter description for `jsonnetfile_parameters` carefully.


== `dashboards.enabled`

[horizontal]
type:: bool
default:: `false`

If the Grafana dashboards should be rendered in a ConfigMap.
This will increase the compile time drastically when enabled.

== `dashboards.namespace`

[horizontal]
type:: string
default:: `syn-thanos`

The namespace in which to create the Grafana dashboard ConfigMaps.

== `commonConfig`

[horizontal]
type:: dict

Common configuration for all Thanos components.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

== `query`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/components/query.md[Query] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

Especially the `stores` list is important as it needs to be populated by the Thanos store API endpoints this Query should use.

=== `enabled`

[horizontal]
type:: bool
default:: `true`

If the Query component should be deployed.

=== `serviceType`

[horizontal]
type:: string
default:: `ClusterIP`

Service type for query service.
Can be used to expose the Query endpoint externally via `LoadBalancer` type.

== `ingress`

[horizontal]
type:: dict

Configuration of an `Ingress` resource intended to expose the Thanos Query frontend.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

Whether the Ingress should be deployed.

=== `host`

[horizontal]
type:: string
default:: ``
required:: yes

The hostname to expose.
This parameter is required and component compilation fails if it's not provided when `enabled` is `true`.

=== `serviceName`

[horizontal]
type:: string
default:: `${_instance}-auth`

The backing service name for the Ingress.

=== `servicePort`

[horizontal]
type:: int
default:: `${thanos:queryRbacProxy:port}`

The backing service port for the Ingress.

=== `annotations`

[horizontal]
type:: dict
default:: `{cert-manager.io/cluster-issuer: letsencrypt-production}`

The annotations of the Ingress resource.

=== `secretName`

[horizontal]
type:: dict
default:: `${_instance}-tls`

The secret name for TLS certificate.
With default annotations this certificate gets provisioned by Let's Encrypt via cert-manager.


== `queryRbacProxy`

[horizontal]
type:: dict

Configuration for the RBAC proxy sidecar that authenticates requests to Thanos Query when exposed.
Users are authenticated with OAuth and authorized using Kubernetes RBAC.
It's recommended to deploy the proxy together with an Ingress.

[NOTE]
Only OpenShift is currently supported.

The proxy redirects browser requests without authentication headers to OpenShift OAuth.
Once authenticated, the proxy does authorization by issueing a `SubjectAccessReview` on behalf of the requesting user against the service named `queryRbacProxy.serviceName`.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

Whether the RBAC should be deployed.

=== `redirectUri`

[horizontal]
type:: string
default:: `https://${thanos:ingress:host}`

The URL which OpenShift OAuth redirects back to after successfully authenticating a user.

=== `serviceName`

[horizontal]
type:: string
default:: `${_instance}-auth`

The resource name of the additional `Service` object that gets created for exposing the querier via RBAC proxy.

=== `port`

[horizontal]
type:: int
default:: `8080`

The port number of the `Service` and proxy sidecar container.

== `objectStorageConfig`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/thanos/storage.md[Object Storage].
See https://thanos.io/tip/thanos/storage.md[Object Storage & Data Format] for available options.
This configuration will be stored in a K8s secret.

== `store`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/components/store.md[Store] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

If the Store component should be deployed.
It will require an `objectStorageConfig` if enabled.

== `compactor`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/components/compact.md[Compactor] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

If the Compactor component should be deployed.
It will require an `objectStorageConfig` if enabled.

== `bucket`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/v0.18/components/tools.md/#bucket-web[Bucket Web] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

If the Bucket Web component should be deployed.
It will require an `objectStorageConfig` if enabled.

== `receive`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/v0.23/components/receive.md/[Receiver] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

If the Receiver component should be deployed.
It will require an `objectStorageConfig` if enabled.

== `images`

[horizontal]
type:: dictionary

Dictionary containing the container images used by this component.


== Example

[source,yaml]
----
parameters:
  thanos:
    namespace: example-namespace
    commonConfig:
      version: v0.17.2
    query:
      replicas: 3
    store:
      enabled: true
    bucket:
      enabled: true
    objectStorageConfig:
      type: S3
      config:
        bucket: thanos-metrics
        endpoint: s3.example.com
        access_key: ?{vaultkv:${cluster:tenant}/${cluster:name}/thanos/access_key}
        secret_key: ?{vaultkv:${cluster:tenant}/${cluster:name}/thanos/secret_key}
----
