= Parameters

The parent key for all of the following parameters is `thanos`.

== `namespace`

[horizontal]
type:: string
default:: `syn-thanos`

The namespace in which to deploy this component.

== `dashboards.enabled`

[horizontal]
type:: bool
default:: `false`

If the Grafana dashboards should be rendered in a ConfigMap.
This will increase the compile time drastically when enabled.

== `dashboards.namespace`

[horizontal]
type:: string
default:: `syn-thanos`

The namespace in which to create the Grafana dashboard ConfigMaps.

== `commonConfig`

[horizontal]
type:: dict

Common configuration for all Thanos components.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

== `query`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/components/query.md[Query] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

Especially the `stores` list is important as it needs to be populated by the Thanos store API endpoints this Query should use.

=== `serviceType`

[horizontal]
type:: string
default:: `ClusterIP`

Service type for query service.
Can be used to expose the Query endpoint externally via `LoadBalancer` type.

== `objectStorageConfig`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/thanos/storage.md[Object Storage].
See https://thanos.io/tip/thanos/storage.md[Object Storage & Data Format] for available options.
This configuration will be stored in a K8s secret.

== `store`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/tip/components/store.md[Store] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

If the Store component should be deployed.
It will require an `objectStorageConfig` if enabled.


== `bucket`

[horizontal]
type:: dict

Configuration for the Thanos https://thanos.io/v0.18/components/tools.md/#bucket-web[Bucket Web] component.
See https://github.com/thanos-io/kube-thanos/blob/master/all.jsonnet[all.jsonnet] for available options.

=== `enabled`

[horizontal]
type:: bool
default:: `false`

If the Bucket Web component should be deployed.
It will require an `objectStorageConfig` if enabled.

== `images`

[horizontal]
type:: dictionary

Dictionary containing the container images used by this component.


== Example

[source,yaml]
----
parameters:
  thanos:
    namespace: example-namespace
    commonConfig:
      version: v0.17.2
    query:
      replicas: 3
    store:
      enabled: true
    bucket:
      enabled: true
    objectStorageConfig:
      type: S3
      config:
        bucket: thanos-metrics
        endpoint: s3.example.com
        access_key: ?{vaultkv:${cluster:tenant}/${cluster:name}/thanos/access_key}
        secret_key: ?{vaultkv:${cluster:tenant}/${cluster:name}/thanos/secret_key}
----
